git:
  depth: 10
branches:
  only:
  - master
  - develop
language: objective-c
env:
- TERM=dumb
before_script:
- brew install ant gradle >brew-install.log
- brew install caskroom/cask/brew-cask
- brew cask install flash-player-debugger
- export FLASHPLAYER_DEBUGGER="$HOME/Applications/Flash Player Debugger.app/Contents/MacOS/Flash Player Debugger"
- export FLASH_PLAYER_EXE="$HOME/Applications/Flash Player Debugger.app/Contents/MacOS/Flash Player Debugger"
- wget -O flex_sdk.zip http://mirrors.gigenet.com/apache/flex/4.14.1/binaries/apache-flex-sdk-4.14.1-bin.zip
- unzip -q flex_sdk.zip -d flex_sdk
- echo env.PLAYERGLOBAL_HOME=libs/player > flex_sdk/env.properties
- mkdir -p flex_sdk/frameworks/libs/player/11.1/
- mkdir -p flex_sdk/frameworks/libs/player/19.0/
- export FLEX_HOME="$TRAVIS_BUILD_DIR/flex_sdk"
- chmod +x flex_sdk/bin/mxmlc
script:
- ant